"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-03 06:05:54.609485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('after_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_table('case_counters',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('last', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('year')
    )
    op.create_table('departments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name_i18n', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('category_coverage', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('method', sa.String(length=8), nullable=False),
    sa.Column('path', sa.String(length=300), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'key', name='uq_idem_user_key')
    )
    op.create_table('wards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('municipality_id', sa.String(length=36), nullable=True),
    sa.Column('boundary', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lon', sa.Float(), nullable=True),
    sa.Column('officer_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], name='fk_wards_officer', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('geometry', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('ward_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('hashed_password', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=True),
    sa.Column('ward_id', sa.String(length=36), nullable=True),
    sa.Column('preferred_language', sa.String(length=16), nullable=False),
    sa.Column('accessibility', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department_id'), 'users', ['department_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_ward_id'), 'users', ['ward_id'], unique=False)
    op.create_table('civic_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('client_case_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('subcategory', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('sla_class', sa.String(length=32), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('location_tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('ward_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=64), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('support_count', sa.Integer(), nullable=False),
    sa.Column('recurrence_count', sa.Integer(), nullable=False),
    sa.Column('reopen_count', sa.Integer(), nullable=False),
    sa.Column('synthetic', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ward_id'], ['wards.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_number'),
    sa.UniqueConstraint('reporter_id', 'client_case_id', name='uq_case_client_id')
    )
    op.create_index('ix_case_dept_status', 'civic_cases', ['department_id', 'status'], unique=False)
    op.create_index('ix_case_geo', 'civic_cases', ['latitude', 'longitude'], unique=False)
    op.create_index(op.f('ix_civic_cases_category'), 'civic_cases', ['category'], unique=False)
    op.create_index(op.f('ix_civic_cases_created_at'), 'civic_cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_civic_cases_department_id'), 'civic_cases', ['department_id'], unique=False)
    op.create_index(op.f('ix_civic_cases_reporter_id'), 'civic_cases', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_civic_cases_status'), 'civic_cases', ['status'], unique=False)
    op.create_index(op.f('ix_civic_cases_ward_id'), 'civic_cases', ['ward_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=48), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('report_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('schema_version', sa.String(length=64), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('degraded', sa.Boolean(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('result_json', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analyses_case_id'), 'ai_analyses', ['case_id'], unique=False)
    op.create_index(op.f('ix_ai_analyses_task_type'), 'ai_analyses', ['task_type'], unique=False)
    op.create_table('case_embeddings',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('vector', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.PrimaryKeyConstraint('case_id')
    )
    op.create_table('case_events',
    sa.Column('seq', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_role', sa.String(length=32), nullable=True),
    sa.Column('visibility', sa.String(length=10), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.PrimaryKeyConstraint('seq'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_case_events_case', 'case_events', ['case_id', 'seq'], unique=False)
    op.create_table('case_relations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_a', sa.String(length=36), nullable=False),
    sa.Column('case_b', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_a'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['case_b'], ['civic_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_a', 'case_b', 'relation_type', name='uq_case_relation')
    )
    op.create_index(op.f('ix_case_relations_case_a'), 'case_relations', ['case_a'], unique=False)
    op.create_index(op.f('ix_case_relations_case_b'), 'case_relations', ['case_b'], unique=False)
    op.create_table('evidence_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('uploader_id', sa.String(length=36), nullable=False),
    sa.Column('work_order_id', sa.String(length=36), nullable=True),
    sa.Column('verification_id', sa.String(length=36), nullable=True),
    sa.Column('purpose', sa.String(length=16), nullable=False),
    sa.Column('object_key', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('media_type', sa.String(length=16), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], name='fk_evidence_work_order', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_key')
    )
    op.create_index(op.f('ix_evidence_items_case_id'), 'evidence_items', ['case_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_uploader_id'), 'evidence_items', ['uploader_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_work_order_id'), 'evidence_items', ['work_order_id'], unique=False)
    op.create_table('incident_cases',
    sa.Column('incident_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('added_by', sa.String(length=64), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('incident_id', 'case_id')
    )
    op.create_table('report_signals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('reporter_id', sa.String(length=36), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('original_language', sa.String(length=16), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_signals_case_id'), 'report_signals', ['case_id'], unique=False)
    op.create_index(op.f('ix_report_signals_reporter_id'), 'report_signals', ['reporter_id'], unique=False)
    op.create_table('supports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id', 'user_id', name='uq_support')
    )
    op.create_index(op.f('ix_supports_case_id'), 'supports', ['case_id'], unique=False)
    op.create_index(op.f('ix_supports_user_id'), 'supports', ['user_id'], unique=False)
    op.create_table('verifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('citizen_id', sa.String(length=36), nullable=False),
    sa.Column('result', sa.String(length=24), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['citizen_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verifications_case_id'), 'verifications', ['case_id'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('department_id', sa.String(length=64), nullable=True),
    sa.Column('assigned_worker_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['civic_cases.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wo_worker_status', 'work_orders', ['assigned_worker_id', 'status'], unique=False)
    op.create_index(op.f('ix_work_orders_case_id'), 'work_orders', ['case_id'], unique=False)
    op.create_index(op.f('ix_work_orders_department_id'), 'work_orders', ['department_id'], unique=False)
    op.create_index(op.f('ix_work_orders_status'), 'work_orders', ['status'], unique=False)
    # circular references (users <-> wards, work_orders <-> evidence_items) are added after both tables exist
    op.create_foreign_key('fk_wards_officer', 'wards', 'users', ['officer_id'], ['id'])
    op.create_foreign_key('fk_evidence_work_order', 'evidence_items', 'work_orders', ['work_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('fk_evidence_work_order', 'evidence_items', type_='foreignkey')
    op.drop_constraint('fk_wards_officer', 'wards', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_status'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_department_id'), table_name='work_orders')
    op.drop_index(op.f('ix_work_orders_case_id'), table_name='work_orders')
    op.drop_index('ix_wo_worker_status', table_name='work_orders')
    op.drop_table('work_orders')
    op.drop_index(op.f('ix_verifications_case_id'), table_name='verifications')
    op.drop_table('verifications')
    op.drop_index(op.f('ix_supports_user_id'), table_name='supports')
    op.drop_index(op.f('ix_supports_case_id'), table_name='supports')
    op.drop_table('supports')
    op.drop_index(op.f('ix_report_signals_reporter_id'), table_name='report_signals')
    op.drop_index(op.f('ix_report_signals_case_id'), table_name='report_signals')
    op.drop_table('report_signals')
    op.drop_table('incident_cases')
    op.drop_index(op.f('ix_evidence_items_work_order_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_uploader_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_case_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_case_relations_case_b'), table_name='case_relations')
    op.drop_index(op.f('ix_case_relations_case_a'), table_name='case_relations')
    op.drop_table('case_relations')
    op.drop_index('ix_case_events_case', table_name='case_events')
    op.drop_table('case_events')
    op.drop_table('case_embeddings')
    op.drop_index(op.f('ix_ai_analyses_task_type'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_case_id'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notif_user_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_civic_cases_ward_id'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_status'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_reporter_id'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_department_id'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_created_at'), table_name='civic_cases')
    op.drop_index(op.f('ix_civic_cases_category'), table_name='civic_cases')
    op.drop_index('ix_case_geo', table_name='civic_cases')
    op.drop_index('ix_case_dept_status', table_name='civic_cases')
    op.drop_table('civic_cases')
    op.drop_index(op.f('ix_users_ward_id'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('incidents')
    op.drop_table('wards')
    op.drop_table('idempotency_keys')
    op.drop_table('departments')
    op.drop_table('case_counters')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
