"""Synthetic phrases: street lighting, parks/trees, public health, traffic, other."""
FAMILIES: dict[str, dict[str, list[str]]] = {}

FAMILIES["light_not_working"] = {
 "en": ["the street light is not working and the road is dark", "streetlights on our lane have been off for a week",
        "no lighting at night, the lamp post is dead", "the lamp near the junction does not turn on",
        "whole stretch is in darkness because the lights are out"],
 "hi": ["स्ट्रीट लाइट बंद है और सड़क पर अंधेरा है", "हमारी गली की स्ट्रीट लाइटें एक हफ्ते से बंद हैं",
        "रात में रोशनी नहीं है, लैंप पोस्ट खराब है", "चौराहे के पास की लाइट जलती ही नहीं",
        "लाइटें बंद होने से पूरा रास्ता अंधेरे में है"],
 "mr": ["पथदिवा बंद आहे आणि रस्त्यावर अंधार आहे", "आमच्या गल्लीतील पथदिवे आठवडाभर बंद आहेत",
        "रात्री उजेड नाही, दिव्याचा खांब बिघडला आहे", "चौकाजवळचा दिवा लागतच नाही",
        "दिवे बंद असल्याने संपूर्ण रस्ता अंधारात आहे"],
 "hl": ["street light band hai aur road par andhera hai", "hamari gali ki streetlights ek hafte se band hain",
        "raat mein roshni nahi hai, lamp post kharab hai", "chauraahe ke paas ki light jalti hi nahi",
        "lights band hone se poora rasta andhere mein hai"],
}
FAMILIES["flickering_light"] = {
 "en": ["the street light keeps flickering on and off", "lamp is blinking continuously all night",
        "the light on the pole flashes and dims repeatedly", "flickering streetlamp is irritating the residents",
        "light bulb on the pole is unstable and flickers"],
 "hi": ["स्ट्रीट लाइट बार-बार टिमटिमा रही है", "लैंप पूरी रात लगातार जलता-बुझता रहता है",
        "खंभे की लाइट बार-बार झपकती और धीमी होती है", "टिमटिमाती स्ट्रीट लाइट से लोग परेशान हैं",
        "खंभे का बल्ब अस्थिर है और झिलमिलाता है"],
 "mr": ["पथदिवा सारखा लुकलुकत आहे", "दिवा रात्रभर सतत चालू-बंद होत असतो",
        "खांबावरचा दिवा वारंवार लुकलुकतो आणि मंद होतो", "लुकलुकणाऱ्या पथदिव्यामुळे रहिवासी त्रस्त आहेत",
        "खांबावरचा बल्ब अस्थिर असून लुकलुकतो"],
 "hl": ["street light baar-baar flicker kar rahi hai", "lamp poori raat lagatar jalta-bujhta rehta hai",
        "khambe ki light baar-baar jhapakti aur dim hoti hai", "flicker karti streetlight se log pareshan hain",
        "khambe ka bulb unstable hai aur jhilmilata hai"],
}
FAMILIES["exposed_live_wire"] = {
 "en": ["a live electric wire is hanging down and sparking", "exposed cable on the pole is touching the ground",
        "the electric junction box is open with bare wires", "loose high tension wire has fallen on the road",
        "wires are dangling from the lamp post and sparks fly when it rains"],
 "hi": ["बिजली का जिंदा तार लटक रहा है और चिंगारी निकल रही है", "खंभे पर खुली केबल जमीन को छू रही है",
        "बिजली का जंक्शन बॉक्स खुला है और नंगे तार दिख रहे हैं", "ढीला हाई टेंशन तार सड़क पर गिर गया है",
        "लैंप पोस्ट से तार लटक रहे हैं और बारिश में चिंगारियाँ उड़ती हैं"],
 "mr": ["विजेची जिवंत तार लटकत आहे आणि ठिणग्या पडत आहेत", "खांबावरची उघडी केबल जमिनीला टेकत आहे",
        "विजेचा जंक्शन बॉक्स उघडा असून उघड्या तारा दिसत आहेत", "सैल उच्च दाबाची तार रस्त्यावर पडली आहे",
        "दिव्याच्या खांबावरून तारा लटकत आहेत आणि पावसात ठिणग्या उडतात"],
 "hl": ["bijli ka zinda taar latak raha hai aur chingaari nikal rahi hai", "khambe par khuli cable zameen ko chhu rahi hai",
        "bijli ka junction box khula hai aur nange taar dikh rahe hain", "dheela high tension taar road par gir gaya hai",
        "lamp post se taar latak rahe hain aur barish mein sparks udte hain"],
}
FAMILIES["fallen_tree"] = {
 "en": ["a big tree has fallen and is blocking the road", "tree branch broke in the storm and fell on the lane",
        "uprooted tree is lying across the street", "a huge branch is hanging dangerously over the footpath",
        "the tree collapsed on a parked car and the road"],
 "hi": ["एक बड़ा पेड़ गिर गया है और सड़क बंद है", "तूफान में पेड़ की डाल टूटकर गली में गिर गई",
        "उखड़ा हुआ पेड़ सड़क के आर-पार पड़ा है", "बहुत बड़ी डाल फुटपाथ के ऊपर खतरनाक तरीके से लटक रही है",
        "पेड़ खड़ी गाड़ी और सड़क पर गिर गया है"],
 "mr": ["मोठे झाड कोसळले असून रस्ता बंद आहे", "वादळात झाडाची फांदी तुटून गल्लीत पडली",
        "उन्मळून पडलेले झाड रस्त्यावर आडवे पडले आहे", "फार मोठी फांदी पदपथावर धोकादायक रीतीने लटकत आहे",
        "झाड उभ्या गाडीवर आणि रस्त्यावर कोसळले आहे"],
 "hl": ["ek bada ped gir gaya hai aur road band hai", "toofan mein ped ki daal tootkar gali mein gir gayi",
        "ukhda hua ped sadak ke aar-paar pada hai", "bahut badi daal footpath ke upar khatarnak tarike se latak rahi hai",
        "ped khadi gaadi aur road par gir gaya hai"],
}
FAMILIES["overgrown_vegetation"] = {
 "en": ["bushes and weeds have overgrown on the roadside", "wild grass is very tall near the compound wall",
        "overgrown plants are blocking the pavement and view", "the park is full of uncut weeds",
        "tall shrubs need trimming as they cover the signboard"],
 "hi": ["सड़क किनारे झाड़ियाँ और घास बहुत बढ़ गई है", "चारदीवारी के पास जंगली घास बहुत ऊँची हो गई है",
        "बढ़े हुए पौधे फुटपाथ और नज़र को रोक रहे हैं", "पार्क में बिना कटी खरपतवार भरी है",
        "ऊँची झाड़ियों की कटाई जरूरी है क्योंकि वे साइनबोर्ड ढक रही हैं"],
 "mr": ["रस्त्याकडेला झुडपे आणि गवत खूप वाढले आहे", "कुंपणाच्या भिंतीजवळ रानटी गवत खूप उंच झाले आहे",
        "वाढलेली झुडपे पदपथ आणि दृश्य अडवत आहेत", "उद्यानात न कापलेले तण भरले आहे",
        "उंच झुडपे छाटणे गरजेचे आहे कारण ती फलक झाकत आहेत"],
 "hl": ["road kinare jhaadiyan aur ghaas bahut badh gayi hai", "boundary wall ke paas jungli ghaas bahut oonchi ho gayi hai",
        "badhe hue paudhe footpath aur nazar ko rok rahe hain", "park mein bina kati khar-patwar bhari hai",
        "oonchi jhaadiyon ki katai zaruri hai kyunki wo signboard dhak rahi hain"],
}
FAMILIES["damaged_park_equipment"] = {
 "en": ["the swing in the children's park is broken", "slide in the garden has rusted and sharp edges",
        "park benches are smashed and unusable", "playground equipment is damaged and unsafe",
        "the see-saw in the park has collapsed"],
 "hi": ["बच्चों के पार्क का झूला टूटा हुआ है", "बगीचे की स्लाइड में जंग लगी है और तेज किनारे निकले हैं",
        "पार्क की बेंचें टूटी हैं और इस्तेमाल लायक नहीं", "खेल के मैदान के उपकरण खराब और असुरक्षित हैं",
        "पार्क का सीसॉ गिर गया है"],
 "mr": ["मुलांच्या उद्यानातील झोका तुटलेला आहे", "बागेतील घसरगुंडीला गंज चढला असून तीक्ष्ण कडा निघाल्या आहेत",
        "उद्यानातील बाके तुटली असून वापरण्यायोग्य नाहीत", "खेळाच्या मैदानातील साधने खराब आणि असुरक्षित आहेत",
        "उद्यानातील सी-सॉ कोसळला आहे"],
 "hl": ["bachchon ke park ka jhoola toota hua hai", "bagiche ki slide mein zang lag gaya hai aur tez kinare nikle hain",
        "park ki benches tooti hain aur istemal layak nahi", "playground ke equipment kharab aur unsafe hain",
        "park ka seesaw gir gaya hai"],
}
FAMILIES["mosquito_breeding"] = {
 "en": ["stagnant water is breeding mosquitoes in our area", "water has collected in the empty plot and mosquitoes are spreading",
        "mosquito menace is high and fogging is needed", "dengue risk because of stagnant puddles near houses",
        "pools of still water full of larvae in the lane"],
 "hi": ["हमारे इलाके में रुके हुए पानी से मच्छर पनप रहे हैं", "खाली प्लॉट में पानी जमा है और मच्छर फैल रहे हैं",
        "मच्छरों का बहुत प्रकोप है और फॉगिंग जरूरी है", "घरों के पास जमा पानी से डेंगू का खतरा है",
        "गली में रुके पानी के गड्ढों में लार्वा भरा है"],
 "mr": ["आमच्या परिसरात साचलेल्या पाण्यामुळे डासांची पैदास होत आहे", "रिकाम्या प्लॉटमध्ये पाणी साचले असून डास पसरत आहेत",
        "डासांचा खूप उपद्रव आहे आणि फवारणी आवश्यक आहे", "घराजवळ साचलेल्या पाण्यामुळे डेंग्यूचा धोका आहे",
        "गल्लीत साचलेल्या पाण्याच्या डबक्यांत अळ्या भरल्या आहेत"],
 "hl": ["hamare area mein ruke hue paani se machhar panap rahe hain", "khaali plot mein paani jama hai aur machhar phail rahe hain",
        "machharon ka bahut prakop hai aur fogging zaruri hai", "gharon ke paas jama paani se dengue ka khatra hai",
        "gali mein ruke paani ke gaddhon mein larvae bhara hai"],
}
FAMILIES["stray_animals"] = {
 "en": ["a pack of stray dogs is chasing people in our street", "stray cattle are roaming and blocking the road",
        "aggressive street dogs bit a child yesterday", "too many stray dogs near the school gate at night",
        "cows sit in the middle of the road and cause jams"],
 "hi": ["आवारा कुत्तों का झुंड हमारी गली में लोगों का पीछा करता है", "आवारा मवेशी घूमते हैं और सड़क रोकते हैं",
        "कल आक्रामक कुत्ते ने एक बच्चे को काट लिया", "रात में स्कूल के गेट के पास बहुत सारे आवारा कुत्ते हैं",
        "गायें बीच सड़क पर बैठी रहती हैं और जाम लग जाता है"],
 "mr": ["भटक्या कुत्र्यांची टोळी आमच्या गल्लीत लोकांच्या मागे लागते", "भटकी गुरे फिरत असतात आणि रस्ता अडवतात",
        "काल आक्रमक कुत्र्याने एका मुलाला चावा घेतला", "रात्री शाळेच्या गेटजवळ खूप भटकी कुत्री असतात",
        "गायी भर रस्त्यात बसतात आणि कोंडी होते"],
 "hl": ["awara kutton ka jhund hamari gali mein logon ka peecha karta hai", "awara maweshi ghoomte hain aur road rokte hain",
        "kal aggressive kutte ne ek bachche ko kaat liya", "raat mein school gate ke paas bahut saare awara kutte hain",
        "gaayen beech road par baithi rehti hain aur jam lag jaata hai"],
}
FAMILIES["open_burning"] = {
 "en": ["someone is burning garbage in the open and the smoke is choking us", "plastic waste is being burnt near the houses",
        "open burning of leaves creates heavy smoke every evening", "fire and smoke from burning trash at the vacant lot",
        "burning of waste in the lane is making breathing difficult"],
 "hi": ["कोई खुले में कचरा जला रहा है और धुएँ से दम घुट रहा है", "घरों के पास प्लास्टिक कचरा जलाया जा रहा है",
        "पत्तों को खुले में जलाने से हर शाम घना धुआँ होता है", "खाली जगह पर कचरा जलाने से आग और धुआँ हो रहा है",
        "गली में कचरा जलाने से सांस लेना मुश्किल हो गया है"],
 "mr": ["कोणीतरी उघड्यावर कचरा जाळत आहे आणि धुराने गुदमरायला होत आहे", "घराजवळ प्लास्टिक कचरा जाळला जात आहे",
        "पाने उघड्यावर जाळल्याने रोज संध्याकाळी दाट धूर होतो", "रिकाम्या जागेत कचरा जाळल्याने आग आणि धूर होत आहे",
        "गल्लीत कचरा जाळल्याने श्वास घेणे कठीण झाले आहे"],
 "hl": ["koi khule mein kachra jala raha hai aur dhuen se dam ghut raha hai", "gharon ke paas plastic kachra jalaya ja raha hai",
        "patton ko khule mein jalane se har shaam ghana dhuan hota hai", "khaali jagah par kachra jalane se aag aur dhuan ho raha hai",
        "gali mein kachra jalane se saans lena mushkil ho gaya hai"],
}
FAMILIES["illegal_parking"] = {
 "en": ["cars are parked illegally and blocking our gate", "vehicles are parked in a no parking zone all day",
        "a truck is parked on the road and causing a jam", "wrongly parked bikes block the entire lane",
        "someone has parked in front of the hospital entrance"],
 "hi": ["गाड़ियाँ गलत तरीके से खड़ी हैं और हमारा गेट रोक रही हैं", "नो पार्किंग जोन में दिन भर वाहन खड़े रहते हैं",
        "सड़क पर ट्रक खड़ा है और जाम लग रहा है", "गलत खड़ी बाइकें पूरी गली रोक रही हैं",
        "किसी ने अस्पताल के प्रवेश द्वार के सामने गाड़ी खड़ी कर दी है"],
 "mr": ["गाड्या बेकायदेशीरपणे उभ्या असून आमचे गेट अडवत आहेत", "नो पार्किंग झोनमध्ये दिवसभर वाहने उभी असतात",
        "रस्त्यावर ट्रक उभा असून कोंडी होत आहे", "चुकीच्या पद्धतीने लावलेल्या दुचाकी संपूर्ण गल्ली अडवत आहेत",
        "कोणीतरी रुग्णालयाच्या प्रवेशद्वारासमोर गाडी उभी केली आहे"],
 "hl": ["gaadiyan galat tarike se khadi hain aur hamara gate rok rahi hain", "no parking zone mein din bhar vehicles khade rehte hain",
        "road par truck khada hai aur jam lag raha hai", "galat khadi bikes poori gali rok rahi hain",
        "kisi ne hospital ke entrance ke saamne gaadi khadi kar di hai"],
}
FAMILIES["footpath_encroachment"] = {
 "en": ["hawkers have occupied the entire footpath", "shop owners have extended their goods onto the pavement",
        "illegal stalls block the walkway and people walk on the road", "encroachment on the sidewalk by a tea stall",
        "construction material is kept on the footpath for weeks"],
 "hi": ["फेरीवालों ने पूरे फुटपाथ पर कब्जा कर लिया है", "दुकानदारों ने सामान फुटपाथ तक फैला दिया है",
        "अवैध ठेले रास्ता रोकते हैं और लोग सड़क पर चलते हैं", "चाय की दुकान ने फुटपाथ पर अतिक्रमण कर लिया है",
        "हफ्तों से फुटपाथ पर निर्माण सामग्री रखी है"],
 "mr": ["फेरीवाल्यांनी संपूर्ण पदपथ व्यापला आहे", "दुकानदारांनी माल पदपथापर्यंत पसरवला आहे",
        "बेकायदेशीर गाडे चालण्याचा मार्ग अडवतात आणि लोक रस्त्यावरून चालतात", "चहाच्या टपरीने पदपथावर अतिक्रमण केले आहे",
        "आठवड्यांपासून पदपथावर बांधकाम साहित्य ठेवले आहे"],
 "hl": ["pheriwalon ne poore footpath par kabza kar liya hai", "dukaandaaron ne saamaan footpath tak phaila diya hai",
        "illegal thele rasta rokte hain aur log road par chalte hain", "chai ki dukaan ne footpath par encroachment kar liya hai",
        "hafton se footpath par construction material rakha hai"],
}
FAMILIES["signal_not_working"] = {
 "en": ["the traffic signal at the junction is not working", "signal lights are dead and traffic is chaotic",
        "traffic light stuck on red for ever", "all three lights of the signal are off at the crossing",
        "the pedestrian signal does not turn green"],
 "hi": ["चौराहे का ट्रैफिक सिग्नल काम नहीं कर रहा", "सिग्नल की लाइटें बंद हैं और ट्रैफिक अव्यवस्थित है",
        "ट्रैफिक लाइट हमेशा लाल पर अटकी हुई है", "क्रॉसिंग पर सिग्नल की तीनों लाइटें बुझी हैं",
        "पैदल यात्री सिग्नल हरा नहीं होता"],
 "mr": ["चौकातील वाहतूक सिग्नल चालू नाही", "सिग्नलचे दिवे बंद असून वाहतूक गोंधळलेली आहे",
        "ट्रॅफिक सिग्नलची लाईट कायम लालवर अडकली आहे", "चौकातील सिग्नलचे तिन्ही दिवे बंद आहेत",
        "पादचारी सिग्नल हिरवा होत नाही"],
 "hl": ["chauraahe ka traffic signal kaam nahi kar raha", "signal ki lights band hain aur traffic ulta-seedha hai",
        "traffic light hamesha ke liye red par atki hai", "crossing par signal ki teeno lights bujhi hain",
        "pedestrian signal green nahi hota"],
}
FAMILIES["unclassified"] = {
 "en": ["something is wrong near my house, please look into it", "I want to complain but I do not know which department",
        "please help, there is a problem in our area", "the neighbours are playing very loud music at night",
        "I need information about the municipal office timings"],
 "hi": ["मेरे घर के पास कुछ गड़बड़ है, कृपया देखिए", "मुझे शिकायत करनी है पर पता नहीं कौन सा विभाग है",
        "कृपया मदद कीजिए, हमारे इलाके में समस्या है", "पड़ोसी रात में बहुत तेज़ संगीत बजाते हैं",
        "मुझे नगर निगम कार्यालय के समय की जानकारी चाहिए"],
 "mr": ["माझ्या घराजवळ काहीतरी बिघडले आहे, कृपया पाहा", "मला तक्रार करायची आहे पण कोणता विभाग माहीत नाही",
        "कृपया मदत करा, आमच्या परिसरात समस्या आहे", "शेजारी रात्री खूप मोठ्याने गाणी लावतात",
        "मला महापालिका कार्यालयाच्या वेळांची माहिती हवी आहे"],
 "hl": ["mere ghar ke paas kuch gadbad hai, please dekhiye", "mujhe complaint karni hai par pata nahi kaun sa department hai",
        "please help kijiye, hamare area mein problem hai", "padosi raat mein bahut tez music bajate hain",
        "mujhe nagar nigam office ke timing ki jaankari chahiye"],
}
