"""Synthetic phrases: sanitation and drainage/sewerage (see lexicon_roads_water.py)."""
FAMILIES: dict[str, dict[str, list[str]]] = {}

FAMILIES["garbage_overflow"] = {
 "en": ["the garbage bin is overflowing onto the street", "waste is piled up around the dustbin and stinking",
        "trash heap has grown huge and is spilling over the road", "the community dumpster has not been cleared and is overflowing",
        "rubbish everywhere, bins are full and flies are spreading"],
 "hi": ["कचरे का डिब्बा भरकर सड़क पर बिखर रहा है", "कूड़ेदान के चारों तरफ कचरा जमा है और बदबू आ रही है",
        "कचरे का ढेर बहुत बड़ा हो गया है और सड़क पर फैल रहा है", "मोहल्ले का कूड़ादान साफ नहीं हुआ और ओवरफ्लो हो रहा है",
        "हर जगह गंदगी है, डिब्बे भरे हैं और मक्खियाँ फैल रही हैं"],
 "mr": ["कचरापेटी भरून रस्त्यावर सांडत आहे", "कचराकुंडीभोवती कचरा साचला असून दुर्गंधी येत आहे",
        "कचऱ्याचा ढीग खूप वाढला असून रस्त्यावर पसरत आहे", "सोसायटीची कचराकुंडी साफ झाली नाही आणि ओसंडून वाहत आहे",
        "सगळीकडे घाण आहे, कुंड्या भरल्या आहेत आणि माश्या पसरत आहेत"],
 "hl": ["kachre ka dibba bharkar sadak par bikhar raha hai", "kooda-dan ke charon taraf kachra jama hai aur badbu aa rahi hai",
        "kachre ka dher bahut bada ho gaya hai aur road par phail raha hai", "mohalle ka dumpster saaf nahi hua aur overflow ho raha hai",
        "har jagah ganda hai, dibbe bhare hain aur makkhiyan phail rahi hain"],
}
FAMILIES["missed_garbage_collection"] = {
 "en": ["the garbage truck did not come to our street today", "door to door waste collection has been missed for a week",
        "nobody has collected the household waste for several days", "the collection vehicle skipped our lane again",
        "garbage has not been picked up from our building"],
 "hi": ["आज हमारी गली में कचरा गाड़ी नहीं आई", "एक हफ्ते से घर-घर कचरा संग्रह नहीं हुआ है",
        "कई दिनों से किसी ने घरों का कचरा नहीं उठाया", "कचरा उठाने वाली गाड़ी फिर हमारी गली छोड़ गई",
        "हमारी बिल्डिंग से कचरा नहीं उठाया गया है"],
 "mr": ["आज आमच्या गल्लीत कचरा गाडी आली नाही", "आठवडाभर घरोघरी कचरा संकलन झालेले नाही",
        "अनेक दिवसांपासून कोणीही घरगुती कचरा उचललेला नाही", "कचरा उचलणारी गाडी पुन्हा आमची गल्ली सोडून गेली",
        "आमच्या इमारतीतून कचरा उचलला गेलेला नाही"],
 "hl": ["aaj hamari gali mein kachra gaadi nahi aayi", "ek hafte se ghar-ghar kachra collection nahi hua hai",
        "kai dinon se kisi ne gharon ka kachra nahi uthaya", "kachra uthane wali gaadi phir hamari gali chhod gayi",
        "hamari building se kachra nahi uthaya gaya hai"],
}
FAMILIES["illegal_dumping"] = {
 "en": ["someone is dumping construction debris on the empty plot", "trucks dump waste at night on the roadside",
        "illegal dumping of rubble and garbage near the river bank", "people keep throwing trash on the vacant land",
        "a pile of demolition waste has been dumped on the footpath"],
 "hi": ["कोई खाली प्लॉट पर निर्माण का मलबा डाल रहा है", "रात में ट्रक सड़क किनारे कचरा फेंक जाते हैं",
        "नदी किनारे मलबा और कचरा अवैध रूप से फेंका जा रहा है", "लोग खाली जमीन पर लगातार कूड़ा फेंक रहे हैं",
        "फुटपाथ पर तोड़फोड़ का मलबा डाल दिया गया है"],
 "mr": ["कोणीतरी रिकाम्या प्लॉटवर बांधकामाचा राडारोडा टाकत आहे", "रात्री ट्रक रस्त्याच्या कडेला कचरा टाकून जातात",
        "नदीकाठी राडारोडा आणि कचरा बेकायदेशीरपणे टाकला जात आहे", "लोक रिकाम्या जागेवर सतत कचरा फेकत आहेत",
        "पदपथावर पाडकामाचा राडारोडा टाकण्यात आला आहे"],
 "hl": ["koi khaali plot par construction ka malba daal raha hai", "raat mein truck road kinare kachra phenk jaate hain",
        "nadi kinare malba aur kachra illegally phenka ja raha hai", "log khaali zameen par lagatar kooda phenk rahe hain",
        "footpath par todfod ka malba daal diya gaya hai"],
}
FAMILIES["dead_animal"] = {
 "en": ["a dead dog is lying on the road and smelling", "carcass of a cow has been lying here since yesterday",
        "there is a dead animal near the bus stop that needs removal", "dead cat on the footpath attracting flies",
        "a dead bird and rat are rotting in the lane"],
 "hi": ["सड़क पर एक मरा हुआ कुत्ता पड़ा है और बदबू आ रही है", "कल से यहाँ गाय की लाश पड़ी हुई है",
        "बस स्टॉप के पास मरा जानवर पड़ा है जिसे हटाना है", "फुटपाथ पर मरी बिल्ली है और मक्खियाँ आ रही हैं",
        "गली में मरा पक्षी और चूहा सड़ रहे हैं"],
 "mr": ["रस्त्यावर मेलेला कुत्रा पडला आहे आणि दुर्गंधी येत आहे", "कालपासून येथे गायीचे मृत शरीर पडले आहे",
        "बस स्टॉपजवळ मृत प्राणी पडला आहे तो हटवायचा आहे", "पदपथावर मेलेली मांजर असून माश्या येत आहेत",
        "गल्लीत मेलेला पक्षी आणि उंदीर कुजत आहेत"],
 "hl": ["road par ek mara hua kutta pada hai aur badbu aa rahi hai", "kal se yahan gaay ki laash padi hui hai",
        "bus stop ke paas mara janwar pada hai jise hatana hai", "footpath par mari billi hai aur makkhiyan aa rahi hain",
        "gali mein mara panchhi aur chuha sad rahe hain"],
}
FAMILIES["blocked_drain"] = {
 "en": ["the drain is blocked and water is not flowing", "the roadside nala is choked with plastic and mud",
        "storm water drain is clogged and the lane gets flooded", "gutter blockage is causing stagnant dirty water",
        "the drainage line is jammed with silt"],
 "hi": ["नाली जाम है और पानी बह नहीं रहा", "सड़क किनारे का नाला प्लास्टिक और कीचड़ से भर गया है",
        "बारिश की नाली चोक है और गली में पानी भर जाता है", "नाली के जाम होने से गंदा पानी रुका हुआ है",
        "ड्रेनेज लाइन गाद से बंद हो गई है"],
 "mr": ["गटार तुंबले आहे आणि पाणी वाहत नाही", "रस्त्याकडेचा नाला प्लास्टिक आणि चिखलाने भरला आहे",
        "पावसाळी गटार तुंबले असून गल्लीत पाणी साचते", "गटार तुंबल्याने घाण पाणी साचून राहिले आहे",
        "ड्रेनेज लाईन गाळाने बंद झाली आहे"],
 "hl": ["naali jam hai aur paani beh nahi raha", "road kinare ka naala plastic aur keechad se bhar gaya hai",
        "barish ki naali choke hai aur gali mein paani bhar jaata hai", "naali jam hone se ganda paani ruka hua hai",
        "drainage line gaad se band ho gayi hai"],
}
FAMILIES["sewage_overflow"] = {
 "en": ["sewage is overflowing from the manhole onto the street", "dirty sewer water is flooding the houses",
        "the sewer line has burst and filthy water is spreading", "raw sewage is coming out of the drain and stinks",
        "sewage water is entering our building compound"],
 "hi": ["मैनहोल से सीवर का पानी सड़क पर बह रहा है", "गंदा सीवर का पानी घरों में घुस रहा है",
        "सीवर लाइन फट गई है और गंदा पानी फैल रहा है", "नाली से कच्चा सीवेज निकल रहा है और बदबू है",
        "सीवेज का पानी हमारी बिल्डिंग के कंपाउंड में आ रहा है"],
 "mr": ["मॅनहोलमधून सांडपाणी रस्त्यावर वाहत आहे", "घाण सांडपाणी घरांमध्ये शिरत आहे",
        "मलनिःसारण वाहिनी फुटली असून घाण पाणी पसरत आहे", "गटारातून मैलापाणी बाहेर येत आहे आणि दुर्गंधी आहे",
        "सांडपाणी आमच्या इमारतीच्या आवारात येत आहे"],
 "hl": ["manhole se sewer ka paani road par beh raha hai", "ganda sewer ka paani gharon mein ghus raha hai",
        "sewer line phat gayi hai aur ganda paani phail raha hai", "naali se kaccha sewage nikal raha hai aur badbu hai",
        "sewage ka paani hamari building ke compound mein aa raha hai"],
}
FAMILIES["missing_manhole_cover"] = {
 "en": ["the manhole cover is missing and the hole is open", "an open manhole without a lid on the main road",
        "the drain cover has been stolen, someone may fall in", "manhole lid is broken and the pit is exposed",
        "uncovered manhole in the lane is a danger to children"],
 "hi": ["मैनहोल का ढक्कन गायब है और गड्ढा खुला है", "मुख्य सड़क पर बिना ढक्कन का खुला मैनहोल है",
        "नाली का ढक्कन चोरी हो गया है, कोई गिर सकता है", "मैनहोल का ढक्कन टूट गया है और गड्ढा दिख रहा है",
        "गली में खुला मैनहोल बच्चों के लिए खतरा है"],
 "mr": ["मॅनहोलचे झाकण गायब आहे आणि खड्डा उघडा आहे", "मुख्य रस्त्यावर झाकणाशिवाय उघडे मॅनहोल आहे",
        "गटाराचे झाकण चोरीला गेले आहे, कोणीतरी पडू शकते", "मॅनहोलचे झाकण तुटले असून खड्डा उघडा पडला आहे",
        "गल्लीतील उघडे मॅनहोल मुलांसाठी धोकादायक आहे"],
 "hl": ["manhole ka dhakkan gayab hai aur gadda khula hai", "main road par bina dhakkan ka khula manhole hai",
        "naali ka dhakkan chori ho gaya hai, koi gir sakta hai", "manhole ka dhakkan toot gaya hai aur gadda dikh raha hai",
        "gali mein khula manhole bachchon ke liye khatra hai"],
}
