"""Canonical training/evaluation schema for external (and synthetic) data.

Every record carries a :class:`Provenance`, so no downstream code can mistake synthetic rows
for real ones. External categories are *never* silently forced into our taxonomy: ``category`` /
``subcategory`` hold the result of an explicit versioned mapping (``mapping_status`` says how),
while the original source labels are kept verbatim in ``source_*`` fields.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

SCHEMA_VERSION = "canonical-data/1"

# real_public: genuine records published by a third party. synthetic: generated by THIS project. synthetic_third_party: synthetically generated by
# someone else (e.g. a competition dataset): never real-world evidence, and never pooled with project-generated synthetic data.
Kind = Literal["real_public", "synthetic", "synthetic_third_party"]
# How the label on the record was obtained
LabelOrigin = Literal["source_category", "mapped_from_source", "human_annotated", "synthetic_template"]
# What the `text` field actually is -- crucial for leakage control
TextOrigin = Literal["citizen_narrative", "source_category_text", "agency_text", "none"]
MappingStatus = Literal["exact", "category_only", "out_of_scope", "unmapped", "not_applicable"]


class _M(BaseModel):
    model_config = ConfigDict(extra="forbid")


class Provenance(_M):
    kind: Kind
    source_id: str
    source_dataset: str
    source_version: str | None = None
    source_record_id: str | None = None
    license_id: str
    license_verified: bool
    origin_verified: bool = True     # False: unclear whether rows are real records (card origin_status=UNVERIFIED_ORIGIN)
    label_origin: LabelOrigin
    mapping_id: str | None = None
    mapping_version: str | None = None
    retrieved_at: str | None = None
    schema_version: str = SCHEMA_VERSION


class CaseRecord(_M):
    """A civic request/report (tabular 311-style or synthetic narrative)."""

    record_id: str
    provenance: Provenance
    text: str | None = None
    text_origin: TextOrigin = "none"
    language: str | None = None
    source_category: str | None = None
    source_subcategory: str | None = None
    source_agency: str | None = None
    category: str | None = None              # mapped (taxonomy v1) or None
    subcategory: str | None = None
    department: str | None = None
    mapping_status: MappingStatus = "unmapped"
    status: str | None = None
    created_at: str | None = None            # ISO-8601, source-local time (tz not stated by most portals)
    closed_at: str | None = None
    latitude: float | None = Field(default=None, ge=-90, le=90)
    longitude: float | None = Field(default=None, ge=-180, le=180)
    duplicate_flag: bool | None = None
    parent_record_id: str | None = None
    place: str | None = None                 # coarse region (borough / community area / city), never an address
    split_hint: Literal["train", "val", "test", "holdout"] | None = None
    # Role-keyed extra fields (e.g. filing_channel, severity, resolution_hours). Usage is governed by the dataset's
    # column-role policy (column_roles.py): which roles may be inputs/targets for which task. Unclassified columns are never stored.
    attributes: dict[str, str | float | int | bool | None] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _consistent(self) -> "CaseRecord":
        if self.text is None and self.text_origin != "none":
            raise ValueError("text_origin must be 'none' when there is no text")
        if self.text is not None and self.text_origin == "none":
            raise ValueError("text present but text_origin is 'none'")
        if self.subcategory and not self.category:
            raise ValueError("subcategory without category")
        if self.mapping_status in ("exact",) and not (self.category and self.subcategory):
            raise ValueError("mapping_status 'exact' requires category and subcategory")
        if self.mapping_status == "category_only" and (not self.category or self.subcategory):
            raise ValueError("mapping_status 'category_only' requires category and no subcategory")
        if self.mapping_status in ("out_of_scope", "unmapped") and (self.category or self.subcategory):
            raise ValueError("unmapped/out_of_scope records must not carry a mapped label")
        return self


class BBox(_M):
    class_code: str
    class_name: str | None = None
    xmin: float
    ymin: float
    xmax: float
    ymax: float
    category: str | None = None
    subcategory: str | None = None
    mapping_status: MappingStatus = "unmapped"
    normalized: bool = False         # True: coordinates are fractions of the image size (YOLO-style sources)

    @model_validator(mode="after")
    def _valid_box(self) -> "BBox":
        if self.xmax <= self.xmin or self.ymax <= self.ymin:
            raise ValueError("degenerate bounding box")
        return self


class ImageRecord(_M):
    """An annotated image. ``image_relpath`` is relative to the externally stored dataset root;
    the image bytes are never copied into the repository."""

    record_id: str
    provenance: Provenance
    image_relpath: str
    width: int | None = None
    height: int | None = None
    country: str | None = None
    capture_context: str | None = None       # e.g. RDD2022 China "MotorBike" / "Drone"
    has_annotation: bool = False
    boxes: list[BBox] = Field(default_factory=list)
    image_labels: list[str] = Field(default_factory=list)   # distinct mapped labels: "cat/sub" or "cat"
    source_labels: list[str] = Field(default_factory=list)  # distinct raw source labels (verbatim)
    group_id: str | None = None      # video / sequence / directory / index-block id: splits must hold out whole groups
    split_hint: Literal["train", "val", "test", "holdout"] | None = None


class PairSide(_M):
    case_id: str
    category: str
    subcategory: str | None = None
    latitude: float = Field(ge=-90, le=90)
    longitude: float = Field(ge=-180, le=180)
    created_at: str
    text: str | None = None
    language: str | None = None
    family_id: str | None = None


class PairRecord(_M):
    pair_id: str
    provenance: Provenance
    label: Literal[0, 1]
    pair_type: str
    cross_language: bool = False
    a: PairSide
    b: PairSide
    split_hint: Literal["train", "val", "test", "holdout"] | None = None
