"""Explicit manifest: dataset -> task -> allowed fields -> labels -> taxonomy mapping -> evaluation track.

BMC rows are DERIVED from the column-role policy (single source of truth); other rows are declared here. The
committed ``TASK_MATRIX.md`` / ``task_matrix.v1.json`` / ``BMC_COLUMN_POLICY.md`` are generated by this module
(``python -m ai.training.src.data_sources.task_matrix --write``) and a test fails if they drift.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

from .card_schema import list_cards, load_card
from .column_roles import TaskPolicy
from .mapping import MappingTable

HERE = Path(__file__).parent
IMG_FORBIDDEN = ["bounding boxes / annotation files", "file or directory names that encode the class", "group id (used only to build splits)"]


def _map_ref(mapping_id: str | None) -> str:
    if not mapping_id:
        return "—"
    try:
        t = MappingTable.load(mapping_id)
        return f"`{t.mapping_id}@{t.version}` ({t.raw['status']})"
    except Exception:
        return f"`{mapping_id}`"


def _static() -> list[dict]:
    def row(source, task, cap, status, inputs, targets, forbidden, labels, mapping, track, implemented, notes=""):
        return {"source_id": source, "task": task, "capability": cap, "status": status, "inputs": inputs, "targets": targets, "forbidden": forbidden,
                "labels": labels, "taxonomy_mapping": _map_ref(mapping), "track": track, "implemented_in_eval_harness": implemented, "notes": notes}
    img = lambda sid, labels, mapping, notes: row(sid, "visual_pothole_eval", "AI-1 (image)", "conditional", ["image bytes"], ["mapped image labels (roads/pothole; cracks → roads)"],  # noqa: E731
                                                  IMG_FORBIDDEN, labels, mapping, "real_holdout", True, notes)
    rows = [
        row("synthetic_civic", "intake_text", "AI-1", "supported", ["text"], ["category", "subcategory"], ["family/place ids (split design only)"],
            "27 taxonomy subcategories (native labels)", None, "synthetic", True, "Hindi/Marathi/Hinglish/English, code-mixing, noise. Never a real-world accuracy claim."),
        row("synthetic_civic", "fusion_pairs", "AI-2", "supported", ["lat/lon", "time", "category", "text"], ["duplicate label"], ["event ids"], "duplicate / not duplicate", None, "synthetic", True,
            "Controlled duplicates incl. cross-language."),
        row("synthetic_civic", "before_after_resolution_evidence", "AI-4", "not_available", [], [], [], "—", None, "none", False,
            "GAP: no synthetic before/after evidence is generated yet (no synthetic images); AI-4 is tested with scripted provider fixtures only. Build later if needed."),
        row("nyc311", "taxonomy_coverage", "AI-3/AI-5", "supported", ["complaint_type", "descriptor"], [], ["address columns (never read)"], "NYC complaint types/descriptors", "nyc311_to_civic", "descriptive", True),
        row("nyc311", "intake_text", "AI-1", "unsupported", [], [], ["category text (label leakage)"], "—", None, "none", False, "No citizen narrative text; category text would be label leakage."),
        row("chicago311", "taxonomy_coverage", "AI-3/AI-5", "supported", ["sr_type"], [], ["address columns (never read)"], "Chicago service request types", "chicago311_to_civic", "descriptive", True),
        row("chicago311", "fusion_pairs", "AI-2", "conditional", ["lat/lon", "created time", "mapped category"], ["agency duplicate/parent link"], ["narrative text (none exists)", "parent fields as inputs"],
            "duplicate / unlinked nearby same-type", "chicago311_to_civic", "real_holdout", True, "Requires duplicate/parent columns (names unconfirmed)."),
        row("rdd2022", "visual_pothole_eval", "AI-1 (image)", "conditional", ["image bytes"], ["mapped image labels (D40 → roads/pothole; D00/D10/D20 → roads)"], IMG_FORBIDDEN,
            "D00, D10, D20, D40", "rdd2022_to_civic", "real_holdout", True, "India subset first; hold out index blocks/countries; provider needed."),
        row("rdd2020", "visual_pothole_eval", "AI-1 (image)", "conditional", ["image bytes"], ["mapped image labels (D40 → roads/pothole; D00/D10/D20 → roads)"], IMG_FORBIDDEN,
            "D00, D10, D20, D40", "rdd2020_to_civic", "real_holdout", True, "India subset; NonCommercial licence reported."),
        img("bharatpothole", "pothole (class names from the dataset's own class file)", "bharatpothole_to_civic", "Positive-only expected; hold out whole videos/sequences."),
        row("mumbai_nashik_road_surface", "visual_road_surface_eval", "AI-1 (image)", "conditional", ["image bytes"], ["mapped image labels (damaged surface → roads; pothole if explicitly labelled)"], IMG_FORBIDDEN,
            "folder/scene labels (paved, unpaved, damaged, speed breaker, water) — hypothesised", "mumbai_nashik_to_civic", "real_holdout", True,
            "Category-level only; speed breakers/paved/unpaved/water are out_of_scope; identity of the dataset needs your confirmation."),
        row("idd", "—", "—", "future", [], [], [], "—", None, "none", False, "Optional/future Indian road-scene/multimodal source; no adapter, no V1 dependency."),
    ]
    return rows


def _bmc_rows(policy: TaskPolicy) -> list[dict]:
    mref = f"{_map_ref('bmc_mumbai_to_civic')}; departments {_map_ref('bmc_mumbai_departments')}"
    out = []
    for t in policy.spec.tasks:
        forb = sorted(policy.effective_forbidden(t.task) - {r.name for r in policy.roles.values() if r.phase in ("sensitive_attribute", "pii_never_read")})
        out.append({"source_id": "bmc_mumbai", "task": t.task, "capability": t.capability, "status": t.status, "inputs": t.inputs, "targets": t.targets,
                    "forbidden": forb + ["every unclassified column", "complainant_profile (sensitive)", "pii (never read)"], "labels": "13 reported complaint categories + departments (unverified)",
                    "taxonomy_mapping": mref, "track": t.track, "implemented_in_eval_harness": t.task in {"taxonomy_coverage", "routing_agreement", "triage_priority_prior", "resolution_time_prior", "recurrence_hotspot"},
                    "requires": t.requires, "requires_any": t.requires_any, "operator_confirmations": t.operator_confirmations, "conditions": t.conditions, "notes": t.notes})
    return out


def build_matrix() -> list[dict]:
    policy = TaskPolicy.load("bmc_mumbai")
    rows = _static() + _bmc_rows(policy)
    order = {c.id: i for i, c in enumerate(sorted(list_cards(), key=lambda c: ({"primary": 0, "secondary": 1, "optional": 2, "future": 3}[c.priority], c.id)))}
    rows.sort(key=lambda r: (order[r["source_id"]], r["task"]))
    for r in rows:
        r["source_priority"] = load_card(r["source_id"]).priority
    return rows


def _cell(x) -> str:
    if isinstance(x, list):
        return ", ".join(f"`{i}`" for i in x) if x else "—"
    return str(x) if x not in (None, "") else "—"


def render_markdown() -> str:
    rows = build_matrix()
    L = ["# Dataset → task → allowed fields → labels → taxonomy mapping → evaluation track", "",
         "> GENERATED by `ai/training/src/data_sources/task_matrix.py` (`--write`); do not edit by hand. BMC rows are derived from `mappings/bmc_mumbai_columns.v1.json`.",
         "> Every licence is UNVERIFIED and no real dataset has been downloaded or profiled. Statuses describe what each dataset COULD legitimately support, not results.", "",
         "Status: `supported` · `conditional` (needs the stated columns/confirmations) · `demo_only` · `unsupported` / `not_pursued` / `not_available` · `future`. "
         "Tracks: `synthetic`, `real_holdout`, `hybrid`, `descriptive`, `none`. **Synthetic and real metrics are never pooled.**", ""]
    cur, notes = None, []

    def flush():
        if notes:
            L.extend([""] + [f"- `{t}`: {n}" for t, n in notes])
            notes.clear()

    for r in rows:
        if r["source_id"] != cur:
            flush()
            cur = r["source_id"]
            c = load_card(cur)
            L += ["", f"## {c.name}", f"`{cur}` · priority **{c.priority}** · licence **{c.license.status}** · origin **{c.origin_status}** · identity **{c.identity_status}**", "",
                  "| task | capability | status | allowed inputs | targets | forbidden | labels | taxonomy mapping | track | in eval harness |", "|---|---|---|---|---|---|---|---|---|---|"]
        L.append(f"| `{r['task']}` | {r['capability']} | {r['status']} | {_cell(r['inputs'])} | {_cell(r['targets'])} | {_cell(r['forbidden'])} | {r['labels']} | {r['taxonomy_mapping']} | "
                 f"{r['track']} | {'yes' if r['implemented_in_eval_harness'] else 'no'} |")
        extra = []
        if r.get("requires") or r.get("requires_any"):
            extra.append(f"requires {_cell(r.get('requires', []) + r.get('requires_any', []))}")
        if r.get("operator_confirmations"):
            extra.append(f"operator must confirm {_cell(r['operator_confirmations'])}")
        extra += r.get("conditions", [])
        if r.get("notes"):
            extra.append(r["notes"])
        if extra:
            notes.append((r["task"], "; ".join(extra)))
    flush()
    L.append("")
    return "\n".join(L)


def render_bmc_policy_markdown() -> str:
    p = TaskPolicy.load("bmc_mumbai")
    L = ["# BMC Mumbai column policy (default-deny)", "",
         "> GENERATED from `mappings/bmc_mumbai_columns.v1.json`. Column NAMES are expectations: the Kaggle page/data dictionary were unreachable. Roles are assigned by alias or by an explicit `--role-map`; "
         "every column no role claims is **unclassified and unavailable to every task**. Not an official BMC source; origin and licence unverified.", "",
         "## Roles and phases", "", "| role | phase | stored in prepared output | note |", "|---|---|---|---|"]
    for r in p.spec.roles:
        L.append(f"| `{r.name}` | {r.phase} | {'yes' if r.store and r.phase not in ('sensitive_attribute', 'pii_never_read') else 'NO'} | {r.description or ''} |")
    L += ["", "Phases: `identifier`/`at_submission` (known when filed) < `post_triage` (assigned after triage) < `post_resolution` (outcomes/events after work starts). "
          "`sensitive_attribute` and `pii_never_read` roles are never read, stored, input or target.", "", "## Per-task permissions", ""]
    for t in p.spec.tasks:
        ins, tgts = p.allowed_roles(t.task)
        L += [f"### `{t.task}` — {t.status} ({t.capability}; track `{t.track}`; max input phase `{t.max_phase}`)", "",
              f"- **allowed inputs:** {_cell(ins)}", f"- **targets:** {_cell(tgts)}", f"- **forbidden (explicit):** {_cell([f for f in t.forbidden])} (+ all sensitive/PII roles)",
              f"- **requires:** {_cell(t.requires + t.requires_any)}" + (f"; operator confirms {_cell(t.operator_confirmations)}" if t.operator_confirmations else ""),
              f"- **leakage checks:** {_cell(t.leakage_checks)}"] + [f"- condition: {c}" for c in t.conditions] + ([f"- {t.notes}"] if t.notes else []) + [""]
    return "\n".join(L)


def write_all() -> None:
    (HERE / "TASK_MATRIX.md").write_text(render_markdown(), encoding="utf-8")
    (HERE / "BMC_COLUMN_POLICY.md").write_text(render_bmc_policy_markdown(), encoding="utf-8")
    (HERE / "task_matrix.v1.json").write_text(json.dumps(build_matrix(), indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


if __name__ == "__main__":
    if "--write" in sys.argv:
        write_all()
        print("wrote TASK_MATRIX.md, BMC_COLUMN_POLICY.md, task_matrix.v1.json")
    else:
        print(render_markdown())
